// <auto-generated />
using System;
using BarberSaas.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarberSaas.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908103750_AddReviews")]
    partial class AddReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarberSaas.Api.Models.ActivityLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerAccountId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImpersonatedByPlatformAdminId")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImpersonatedByPlatformAdminId");

                    b.HasIndex("BusinessId", "CreatedAt");

                    b.HasIndex("CustomerAccountId", "CreatedAt");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Appointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CancelToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("PendingCancellationApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("RecurringSeriesId")
                        .HasColumnType("text");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CancelToken")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecurringSeriesId", "Date");

                    b.HasIndex("BusinessId", "Date", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("IX_Appointments_BusinessId_Date_StartTime_Confirmed")
                        .HasFilter("\"Status\" = 'CONFIRMED'");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.BlockedSlot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("EndTime")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("StartTime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("BlockedSlots");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Break", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Breaks");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Business", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BusinessModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Appointment");

                    b.Property<string>("BusinessTypeId")
                        .HasColumnType("text");

                    b.Property<string>("CardcomLastLowProfileId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CardcomNextChargeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CardcomToken")
                        .HasColumnType("text");

                    b.Property<string>("ChatbotConfirmationMessage")
                        .HasColumnType("text");

                    b.Property<bool>("ChatbotEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ChatbotWelcomeMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<int?>("MaxBookingsPerDay")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxBookingsPerWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<double>("RatingAverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("RequireApprovalOnCustomerCancel")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TwilioNumber")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<bool>("WaitlistEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BusinessModel");

                    b.HasIndex("BusinessTypeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.BusinessEmailOtp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email", "CreatedAt");

                    b.ToTable("BusinessEmailOtps");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.BusinessOwnerRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BusinessDescription")
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessTypeId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBusinessId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerFamilyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedByPlatformAdminId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemNeeds")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessTypeId");

                    b.HasIndex("CreatedBusinessId");

                    b.HasIndex("Email");

                    b.HasIndex("ReviewedByPlatformAdminId");

                    b.HasIndex("Status");

                    b.ToTable("BusinessOwnerRequests");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.BusinessPasswordResetOtp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email", "CreatedAt");

                    b.ToTable("BusinessPasswordResetOtps");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.BusinessTypeDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayNameHe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("BusinessTypeDefinitions");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerAccountId")
                        .HasColumnType("text");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("BusinessId", "Phone")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.CustomerAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("CustomerAccounts");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Follow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("CustomerAccountId", "BusinessId")
                        .IsUnique();

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBookable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameHe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.ItemGalleryPhoto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemGalleryPhotos");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.PlatformAdmin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("PlatformAdmins");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.RecurringSeries", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastGeneratedThrough")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ItemId");

                    b.HasIndex("BusinessId", "IsActive");

                    b.ToTable("RecurringSeries");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.RecurringSkip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecurringSeriesId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecurringSeriesId");

                    b.ToTable("RecurringSkips");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("OwnerRepliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerReply")
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("CustomerAccountId", "BusinessId")
                        .IsUnique();

                    b.HasIndex("BusinessId", "IsHidden", "CreatedAt");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.WaitlistEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("AppointmentId", "CustomerAccountId")
                        .IsUnique();

                    b.ToTable("WaitlistEntries");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.WhatsAppBookingToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ItemId");

                    b.ToTable("WhatsAppBookingTokens");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.WhatsAppConversationState", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId", "Phone")
                        .IsUnique();

                    b.ToTable("WhatsAppConversationStates");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.WorkingHours", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.ActivityLog", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BarberSaas.Api.Models.CustomerAccount", "CustomerAccount")
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BarberSaas.Api.Models.PlatformAdmin", "ImpersonatedByPlatformAdmin")
                        .WithMany()
                        .HasForeignKey("ImpersonatedByPlatformAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Business");

                    b.Navigation("CustomerAccount");

                    b.Navigation("ImpersonatedByPlatformAdmin");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Appointment", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Business", "Business")
                        .WithMany("Appointments")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberSaas.Api.Models.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberSaas.Api.Models.Item", "Item")
                        .WithMany("Appointments")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberSaas.Api.Models.RecurringSeries", "RecurringSeries")
                        .WithMany("Appointments")
                        .HasForeignKey("RecurringSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Business");

                    b.Navigation("Customer");

                    b.Navigation("Item");

                    b.Navigation("RecurringSeries");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.BlockedSlot", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Business", "Business")
                        .WithMany("BlockedSlots")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Break", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Business", "Business")
                        .WithMany("Breaks")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Business", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.BusinessTypeDefinition", "BusinessType")
                        .WithMany("Businesses")
                        .HasForeignKey("BusinessTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BusinessType");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.BusinessOwnerRequest", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.BusinessTypeDefinition", "BusinessType")
                        .WithMany()
                        .HasForeignKey("BusinessTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BarberSaas.Api.Models.Business", "CreatedBusiness")
                        .WithMany()
                        .HasForeignKey("CreatedBusinessId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BarberSaas.Api.Models.PlatformAdmin", "ReviewedByPlatformAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByPlatformAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BusinessType");

                    b.Navigation("CreatedBusiness");

                    b.Navigation("ReviewedByPlatformAdmin");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Customer", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Business", "Business")
                        .WithMany("Customers")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberSaas.Api.Models.CustomerAccount", "CustomerAccount")
                        .WithMany("Profiles")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Business");

                    b.Navigation("CustomerAccount");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Follow", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Business", "Business")
                        .WithMany("Follows")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberSaas.Api.Models.CustomerAccount", "CustomerAccount")
                        .WithMany("Follows")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("CustomerAccount");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Item", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Business", "Business")
                        .WithMany("Items")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.ItemGalleryPhoto", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Item", "Item")
                        .WithMany("GalleryPhotos")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.RecurringSeries", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Business", "Business")
                        .WithMany("RecurringSeries")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberSaas.Api.Models.Customer", "Customer")
                        .WithMany("RecurringSeries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberSaas.Api.Models.Item", "Item")
                        .WithMany("RecurringSeries")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Customer");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.RecurringSkip", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.RecurringSeries", "RecurringSeries")
                        .WithMany("Skips")
                        .HasForeignKey("RecurringSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecurringSeries");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Review", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberSaas.Api.Models.Business", "Business")
                        .WithMany("Reviews")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberSaas.Api.Models.CustomerAccount", "CustomerAccount")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Business");

                    b.Navigation("CustomerAccount");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.WaitlistEntry", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Appointment", "Appointment")
                        .WithMany("WaitlistEntries")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberSaas.Api.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberSaas.Api.Models.CustomerAccount", "CustomerAccount")
                        .WithMany("WaitlistEntries")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Business");

                    b.Navigation("CustomerAccount");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.WhatsAppBookingToken", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberSaas.Api.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.WhatsAppConversationState", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.WorkingHours", b =>
                {
                    b.HasOne("BarberSaas.Api.Models.Business", "Business")
                        .WithMany("WorkingHours")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Appointment", b =>
                {
                    b.Navigation("WaitlistEntries");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Business", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BlockedSlots");

                    b.Navigation("Breaks");

                    b.Navigation("Customers");

                    b.Navigation("Follows");

                    b.Navigation("Items");

                    b.Navigation("RecurringSeries");

                    b.Navigation("Reviews");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.BusinessTypeDefinition", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("RecurringSeries");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.CustomerAccount", b =>
                {
                    b.Navigation("Follows");

                    b.Navigation("Profiles");

                    b.Navigation("Reviews");

                    b.Navigation("WaitlistEntries");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.Item", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("GalleryPhotos");

                    b.Navigation("RecurringSeries");
                });

            modelBuilder.Entity("BarberSaas.Api.Models.RecurringSeries", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Skips");
                });
#pragma warning restore 612, 618
        }
    }
}
